# Generated by Django 2.1.5 on 2019-02-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scores', '0003_auto_20190208_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='mInnings',
        ),
        migrations.AddField(
            model_name='batting1',
            name='mInnings',
            field=models.SmallIntegerField(default=1, verbose_name='Innings'),
            preserve_default=False,
        ),
    ]
